In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('merged_df.csv')

In [3]:
df.columns

Index(['Local Timestamp Central Time (Interval Ending)',
       'UTC Timestamp (Interval Ending)',
       'Local Timestamp Central Time (Interval Beginning)', 'Local Date',
       'Hour Number', 'Total Generation (MW)', 'Biomass Generation (MW)',
       'Coal Generation (MW)', 'Gas Generation (MW)', 'Gas-CC Generation (MW)',
       'Hydro Generation (MW)', 'Nuclear Generation (MW)',
       'Other Generation (MW)', 'Solar Generation (MW)',
       'Wind Generation (MW)', 'Bus average LMP_x', 'Houston LMP_x',
       'Hub average LMP_x', 'North LMP_x', 'Panhandle LMP_x', 'South LMP_x',
       'West LMP_x', 'TOTAL Actual Load (MW)', 'Coast Actual Load (MW)',
       'East Actual Load (MW)', 'Far West Actual Load (MW)',
       'North Actual Load (MW)', 'North Central Actual Load (MW)',
       'Southern Actual Load (MW)', 'South Central Actual Load (MW)',
       'West Actual Load (MW)', 'Bus average LMP_y', 'Houston LMP_y',
       'Hub average LMP_y', 'North LMP_y', 'Panhandle LMP_y', 'South LMP_y',
       'West LMP_y', 'SystemTotal Forecast Load (MW)',
       'Houston Forecast Load (MW)', 'North Forecast Load (MW)',
       'South Forecast Load (MW)', 'West Forecast Load (MW)',
       'Comision Federal de Electricidad, Laredo Net Export (MW)',
       'Comision Federal de Electricidad, Railroad Net Export (MW)',
       'Southwest Power Pool, East Net Export (MW)',
       'Southwest Power Pool, North Net Export (MW)',
       'Average Temperature (Fahrenheit)',
       'Dallas / Fort Worth Temperature (Fahrenheit)',
       'Dallas / Fort Worth Temperature Observation Time (Central)',
       'Houston International Airport Temperature (Fahrenheit)',
       'Houston International Airport Temperature Observation Time (Central)',
       'TOTAL Actual Load (MW)_lag1', 'Year', 'Month', 'Day', 'Hour',
       'DayOfWeek', 'DayOfYear', 'IsWeekend', 'Month_sin', 'Month_cos',
       'Hour_sin', 'Hour_cos', 'DayOfWeek_sin', 'DayOfWeek_cos'],
      dtype='object')

In [4]:
df.head(20)

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),...,Hour,DayOfWeek,DayOfYear,IsWeekend,Month_sin,Month_cos,Hour_sin,Hour_cos,DayOfWeek_sin,DayOfWeek_cos
0,2021-03-30 13:00:00,3/30/2021 17:15,3/30/2021 12:00,3/30/2021,13,162449.76058,99.305516,30638.785592,9368.176724,42215.318880,...,13,1,89,0,1.0,6.123234e-17,-0.258819,-9.659258e-01,0.781831,0.623490
1,2021-03-30 14:00:00,3/30/2021 18:15,3/30/2021 13:00,3/30/2021,14,165833.01863,105.794500,31253.448100,9125.563332,47434.423340,...,14,1,89,0,1.0,6.123234e-17,-0.500000,-8.660254e-01,0.781831,0.623490
2,2021-03-30 15:00:00,3/30/2021 19:15,3/30/2021 14:00,3/30/2021,15,168894.35321,107.544116,33190.147680,9889.303080,50777.592360,...,15,1,89,0,1.0,6.123234e-17,-0.707107,-7.071068e-01,0.781831,0.623490
3,2021-03-30 16:00:00,3/30/2021 20:15,3/30/2021 15:00,3/30/2021,16,171731.26712,108.993848,34135.815652,12646.939040,53179.842620,...,16,1,89,0,1.0,6.123234e-17,-0.866025,-5.000000e-01,0.781831,0.623490
4,2021-03-30 17:00:00,3/30/2021 21:15,3/30/2021 16:00,3/30/2021,17,174894.91445,109.167588,34200.205204,17101.383700,53928.048540,...,17,1,89,0,1.0,6.123234e-17,-0.965926,-2.588190e-01,0.781831,0.623490
5,2021-03-30 18:00:00,3/30/2021 22:15,3/30/2021 17:00,3/30/2021,18,176219.15447,109.130212,34120.840828,16747.149452,53836.017940,...,18,1,89,0,1.0,6.123234e-17,-1.000000,-1.836970e-16,0.781831,0.623490
6,2021-03-30 19:00:00,3/30/2021 23:15,3/30/2021 18:00,3/30/2021,19,175092.71325,109.676308,33913.718220,12620.277004,54162.154600,...,19,1,89,0,1.0,6.123234e-17,-0.965926,2.588190e-01,0.781831,0.623490
7,2021-03-30 20:00:00,3/31/2021 0:15,3/30/2021 19:00,3/30/2021,20,174903.01869,109.792204,33804.397748,10422.931016,53755.251310,...,20,1,89,0,1.0,6.123234e-17,-0.866025,5.000000e-01,0.781831,0.623490
8,2021-03-30 21:00:00,3/31/2021 1:15,3/30/2021 20:00,3/30/2021,21,177710.53659,110.088368,33235.518280,7112.802380,51418.657680,...,21,1,89,0,1.0,6.123234e-17,-0.707107,7.071068e-01,0.781831,0.623490
9,2021-03-30 22:00:00,3/31/2021 2:15,3/30/2021 21:00,3/30/2021,22,172895.06145,110.303588,28618.779692,4887.006536,45039.332230,...,22,1,89,0,1.0,6.123234e-17,-0.500000,8.660254e-01,0.781831,0.623490
10,2021-03-30 23:00:00,3/31/2021 3:15,3/30/2021 22:00,3/30/2021,23,162503.46190,110.490836,26699.127016,3915.228368,36195.506872,...,23,1,89,0,1.0,6.123234e-17,-0.258819,9.659258e-01,0.781831,0.623490
11,2021-03-31 00:00:00,3/31/2021 4:15,3/30/2021 23:00,3/30/2021,24,151369.45800,110.713520,28409.314992,3759.557096,24652.246852,...,0,2,90,0,1.0,6.123234e-17,0.000000,1.000000e+00,0.974928,-0.222521
12,2021-03-31 01:00:00,3/31/2021 5:15,3/31/2021 0:00,3/31/2021,1,141724.02021,110.788936,25549.505772,3454.626620,18842.416608,...,1,2,90,0,1.0,6.123234e-17,0.258819,9.659258e-01,0.974928,-0.222521
13,2021-03-31 02:00:00,3/31/2021 6:15,3/31/2021 1:00,3/31/2021,2,135424.42276,110.886996,20196.892616,2556.998460,17739.921888,...,2,2,90,0,1.0,6.123234e-17,0.500000,8.660254e-01,0.974928,-0.222521
14,2021-03-31 03:00:00,3/31/2021 7:15,3/31/2021 2:00,3/31/2021,3,131857.15439,111.036644,17442.040796,2524.472548,17460.799932,...,3,2,90,0,1.0,6.123234e-17,0.707107,7.071068e-01,0.974928,-0.222521
15,2021-03-31 04:00:00,3/31/2021 8:15,3/31/2021 3:00,3/31/2021,4,130583.16496,111.115496,17126.123836,2429.863220,17159.819076,...,4,2,90,0,1.0,6.123234e-17,0.866025,5.000000e-01,0.974928,-0.222521
16,2021-03-31 05:00:00,3/31/2021 9:15,3/31/2021 4:00,3/31/2021,5,132530.96548,110.449304,18442.093340,2537.293948,19020.321488,...,5,2,90,0,1.0,6.123234e-17,0.965926,2.588190e-01,0.974928,-0.222521
17,2021-03-31 06:00:00,3/31/2021 10:15,3/31/2021 5:00,3/31/2021,6,137561.14287,110.992552,21673.542572,4259.354696,22004.360912,...,6,2,90,0,1.0,6.123234e-17,1.000000,6.123234e-17,0.974928,-0.222521
18,2021-03-31 07:00:00,3/31/2021 11:15,3/31/2021 6:00,3/31/2021,7,147657.19372,111.011828,22929.342008,5397.454760,33221.971896,...,7,2,90,0,1.0,6.123234e-17,0.965926,-2.588190e-01,0.974928,-0.222521
19,2021-03-31 08:00:00,3/31/2021 12:15,3/31/2021 7:00,3/31/2021,8,154096.82102,103.745564,27043.038244,5290.681428,35864.521632,...,8,2,90,0,1.0,6.123234e-17,0.866025,-5.000000e-01,0.974928,-0.222521

In [5]:
last_known_features = df.tail(7)

In [6]:
last_known_features

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),...,Hour,DayOfWeek,DayOfYear,IsWeekend,Month_sin,Month_cos,Hour_sin,Hour_cos,DayOfWeek_sin,DayOfWeek_cos
23928,2024-07-31 17:00:00,7/31/2024 21:15,7/31/2024 16:00,7/31/2024,17,319934.63928,20.339764,30389.324124,26333.919428,99622.40916,...,17,2,213,0,-0.5,-0.866025,-0.965926,-2.588190e-01,0.974928,-0.222521
23929,2024-07-31 18:00:00,7/31/2024 22:15,7/31/2024 17:00,7/31/2024,18,318444.40137,20.371096,32085.637564,27000.544704,100915.23093,...,18,2,213,0,-0.5,-0.866025,-1.000000,-1.836970e-16,0.974928,-0.222521
23930,2024-07-31 19:00:00,7/31/2024 23:15,7/31/2024 18:00,7/31/2024,19,313045.98712,20.408840,38456.674644,28428.394516,103190.33546,...,19,2,213,0,-0.5,-0.866025,-0.965926,2.588190e-01,0.974928,-0.222521
23931,2024-07-31 20:00:00,8/1/2024 0:15,7/31/2024 19:00,7/31/2024,20,301741.85866,20.424080,43173.344700,34013.452116,104569.57499,...,20,2,213,0,-0.5,-0.866025,-0.866025,5.000000e-01,0.974928,-0.222521
23932,2024-07-31 21:00:00,8/1/2024 1:15,7/31/2024 20:00,7/31/2024,21,291188.91455,20.416192,44701.886290,34852.092220,104868.37850,...,21,2,213,0,-0.5,-0.866025,-0.707107,7.071068e-01,0.974928,-0.222521
23933,2024-07-31 22:00:00,8/1/2024 2:15,7/31/2024 21:00,7/31/2024,22,283163.73221,20.448760,38671.765218,31612.405848,103780.31964,...,22,2,213,0,-0.5,-0.866025,-0.500000,8.660254e-01,0.974928,-0.222521
23934,2024-07-31 23:00:00,8/1/2024 3:15,7/31/2024 22:00,7/31/2024,23,268072.69886,20.428672,30146.964940,25336.670864,99274.74130,...,23,2,213,0,-0.5,-0.866025,-0.258819,9.659258e-01,0.974928,-0.222521

In [15]:
features = [ 'Biomass Generation (MW)', 'Coal Generation (MW)', 'Gas Generation (MW)', 'Gas-CC Generation (MW)', 'Hydro Generation (MW)', 'Solar Generation (MW)', 'Bus average LMP_y', 'Houston LMP_y', 'Hub average LMP_y', 'North LMP_y', 'Panhandle LMP_y', 'South LMP_y', 'West LMP_y', 'Average Temperature (Fahrenheit)', 'Hour', 'Month_sin', 'Month_cos', 'Hour_sin']

lag_hours = 24

# Create lagged features for each of the specified features
lagged_features = {}
for feature in features:
    lagged_features[feature + '_lag1'] = df[feature].shift(lag_hours)

# Add the lagged features to the dataframe
df_lagged = df.copy()
df_lagged = df_lagged.assign(**lagged_features)

In [13]:
df.head()

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),...,Hour,DayOfWeek,DayOfYear,IsWeekend,Month_sin,Month_cos,Hour_sin,Hour_cos,DayOfWeek_sin,DayOfWeek_cos
0,2021-03-30 13:00:00,3/30/2021 17:15,3/30/2021 12:00,3/30/2021,13,162449.76058,99.305516,30638.785592,9368.176724,42215.31888,...,13,1,89,0,1.0,6.123234e-17,-0.258819,-0.965926,0.781831,0.62349
1,2021-03-30 14:00:00,3/30/2021 18:15,3/30/2021 13:00,3/30/2021,14,165833.01863,105.794500,31253.448100,9125.563332,47434.42334,...,14,1,89,0,1.0,6.123234e-17,-0.500000,-0.866025,0.781831,0.62349
2,2021-03-30 15:00:00,3/30/2021 19:15,3/30/2021 14:00,3/30/2021,15,168894.35321,107.544116,33190.147680,9889.303080,50777.59236,...,15,1,89,0,1.0,6.123234e-17,-0.707107,-0.707107,0.781831,0.62349
3,2021-03-30 16:00:00,3/30/2021 20:15,3/30/2021 15:00,3/30/2021,16,171731.26712,108.993848,34135.815652,12646.939040,53179.84262,...,16,1,89,0,1.0,6.123234e-17,-0.866025,-0.500000,0.781831,0.62349
4,2021-03-30 17:00:00,3/30/2021 21:15,3/30/2021 16:00,3/30/2021,17,174894.91445,109.167588,34200.205204,17101.383700,53928.04854,...,17,1,89,0,1.0,6.123234e-17,-0.965926,-0.258819,0.781831,0.62349

In [12]:
df_lagged.head(20)

,Local Timestamp Central Time (Interval Ending),UTC Timestamp (Interval Ending),Local Timestamp Central Time (Interval Beginning),Local Date,Hour Number,Total Generation (MW),Biomass Generation (MW),Coal Generation (MW),Gas Generation (MW),Gas-CC Generation (MW),...,Hub average LMP_y_lag1,North LMP_y_lag1,Panhandle LMP_y_lag1,South LMP_y_lag1,West LMP_y_lag1,Average Temperature (Fahrenheit)_lag1,Hour_lag1,Month_sin_lag1,Month_cos_lag1,Hour_sin_lag1
0,2021-03-30 13:00:00,3/30/2021 17:15,3/30/2021 12:00,3/30/2021,13,162449.76058,99.305516,30638.785592,9368.176724,42215.318880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-03-30 14:00:00,3/30/2021 18:15,3/30/2021 13:00,3/30/2021,14,165833.01863,105.794500,31253.448100,9125.563332,47434.423340,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-03-30 15:00:00,3/30/2021 19:15,3/30/2021 14:00,3/30/2021,15,168894.35321,107.544116,33190.147680,9889.303080,50777.592360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-03-30 16:00:00,3/30/2021 20:15,3/30/2021 15:00,3/30/2021,16,171731.26712,108.993848,34135.815652,12646.939040,53179.842620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-03-30 17:00:00,3/30/2021 21:15,3/30/2021 16:00,3/30/2021,17,174894.91445,109.167588,34200.205204,17101.383700,53928.048540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021-03-30 18:00:00,3/30/2021 22:15,3/30/2021 17:00,3/30/2021,18,176219.15447,109.130212,34120.840828,16747.149452,53836.017940,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021-03-30 19:00:00,3/30/2021 23:15,3/30/2021 18:00,3/30/2021,19,175092.71325,109.676308,33913.718220,12620.277004,54162.154600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021-03-30 20:00:00,3/31/2021 0:15,3/30/2021 19:00,3/30/2021,20,174903.01869,109.792204,33804.397748,10422.931016,53755.251310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021-03-30 21:00:00,3/31/2021 1:15,3/30/2021 20:00,3/30/2021,21,177710.53659,110.088368,33235.518280,7112.802380,51418.657680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021-03-30 22:00:00,3/31/2021 2:15,3/30/2021 21:00,3/30/2021,22,172895.06145,110.303588,28618.779692,4887.006536,45039.332230,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2021-03-30 23:00:00,3/31/2021 3:15,3/30/2021 22:00,3/30/2021,23,162503.46190,110.490836,26699.127016,3915.228368,36195.506872,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2021-03-31 00:00:00,3/31/2021 4:15,3/30/2021 23:00,3/30/2021,24,151369.45800,110.713520,28409.314992,3759.557096,24652.246852,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2021-03-31 01:00:00,3/31/2021 5:15,3/31/2021 0:00,3/31/2021,1,141724.02021,110.788936,25549.505772,3454.626620,18842.416608,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021-03-31 02:00:00,3/31/2021 6:15,3/31/2021 1:00,3/31/2021,2,135424.42276,110.886996,20196.892616,2556.998460,17739.921888,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2021-03-31 03:00:00,3/31/2021 7:15,3/31/2021 2:00,3/31/2021,3,131857.15439,111.036644,17442.040796,2524.472548,17460.799932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2021-03-31 04:00:00,3/31/2021 8:15,3/31/2021 3:00,3/31/2021,4,130583.16496,111.115496,17126.123836,2429.863220,17159.819076,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2021-03-31 05:00:00,3/31/2021 9:15,3/31/2021 4:00,3/31/2021,5,132530.96548,110.449304,18442.093340,2537.293948,19020.321488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2021-03-31 06:00:00,3/31/2021 10:15,3/31/2021 5:00,3/31/2021,6,137561.14287,110.992552,21673.542572,4259.354696,22004.360912,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2021-03-31 07:00:00,3/31/2021 11:15,3/31/2021 6:00,3/31/2021,7,147657.19372,111.011828,22929.342008,5397.454760,33221.971896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2021-03-31 08:00:00,3/31/2021 12:15,3/31/2021 7:00,3/31/2021,8,154096.82102,103.745564,27043.038244,5290.681428,35864.521632,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(23935, 66)

In [9]:

total_sum = df['Total Generation (MW)'].sum()

print(total_sum)

4669996415.10103

In [13]:
df['Local Date'] = pd.to_datetime(df['Local Timestamp Central Time (Interval Beginning)'], format='%m/%d/%Y %H:%M')

df['Year'] = df['Local Date'].dt.year

yearly_load = df.groupby('Year')['Total Generation (MW)'].sum()

for year in [2021, 2022, 2023, 2024]:
    if year in yearly_load:
        print(f"Total Generation for {year}: {yearly_load[year]} MW")
    else:
        print(f"No data available for the year {year}")

import pandas as pd

Total Generation for 2021: 1222892397.47932 MW
Total Generation for 2022: 1322293411.94918 MW
Total Generation for 2023: 1366088130.21444 MW
Total Generation for 2024: 758722475.45809 MW